name: Build and Push Docker Image

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ published ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Test Docker image
        if: github.event_name != 'pull_request'
        run: |
          # 获取第一个标签（通常是分支名或latest）
          FIRST_TAG=$(echo '${{ steps.meta.outputs.tags }}' | cut -d' ' -f1)
          echo "Testing image: $FIRST_TAG"
          
          # 运行容器并等待启动
          docker run --rm -d --name test-container -p 3456:3456 $FIRST_TAG
          
          # 等待服务启动（最多30秒）
          for i in {1..30}; do
            if curl -f http://localhost:3456 > /dev/null 2>&1; then
              echo "Service is ready after $i seconds"
              break
            fi
            echo "Waiting for service to start... ($i/30)"
            sleep 1
          done
          
          # 最终检查
          curl -f http://localhost:3456 || exit 1
          docker stop test-container